MVCMovieGallery/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBookGallery.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

MVCMovieGallery/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBookGallery.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string SeriesTitle { get; set; }
        public int IssueNumber { get; set; }
        public string DescriptionHtml { get; set; }
        public Artist[] Artists { get; set; }
        public bool Favourite { get; set; }

        public string DisplayText
        {
            get
            {
                return SeriesTitle + " #" + IssueNumber;
            }
        }
        public string CoverImageFileName
        {
            get
            {
                return SeriesTitle.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg";
            }
        }
    }
}

MVCMovieGallery/Controllers/BookGalleryController.cs
using MVCBookGallery.Models;
using MVCMovieGallery.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBookGallery.Controllers
{
    public class BookGalleryController : Controller
    {
        private BookRepository _bookRepository = null;

        public BookGalleryController()
        {
            _bookRepository = new BookRepository();
        }

        public ActionResult Index()
        {
            var books = _bookRepository.GetBooks();

            return View(books);
        }
        public ActionResult Detail(int? id)
        {
            if(id == null)
            {
                return HttpNotFound();
            }

            var book = _bookRepository.GetBook((int)id);

            return View(book);
            
        }
    }
}

MVCMovieGallery/Controllers/MVCBookGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBookGallery.Controllers
{
    public class MVCBookGalleryController : Controller
    {
        public string Detail()
        {
            return "Hello from book controller";
        }
    }
}

MVCMovieGallery/Views/BookGallery/Detail.cshtml
@model MVCBookGallery.Models.Book
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Book Details";
    ViewBag.ShowBackBar = true;
}

<h2>@Model.DisplayText</h2>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h5><label>Series Title:</label> @Model.SeriesTitle</h5>
            <h5><label>Issue #:</label> @Model.IssueNumber</h5>
            <h5><label>Favorite:</label> @(Model.Favourite ? "Yes" : "No")</h5>
            @if (Model.Artists.Length > 0)
            {
            <h5>Artists:</h5>
            <div>
                <ul>
                    @foreach (var artist in Model.Artists)
                    {
                        <li>@artist.Role: @artist.Name  </li>
                    }
                </ul>
            </div>

            }
        </div>
        <h5>Description: </h5>
        <div>@Html.Raw(Model.DescriptionHtml)</div>
    </div>
    <div class="col-md-6">
        <img src="/Images/@Model.CoverImageFileName"
             alt="@Model.DisplayText" class="img-responsive" />
    </div>
</div>

MVCMovieGallery/Views/BookGallery/Index.cshtml
@model MVCBookGallery.Models.Book[]
@{
    ViewBag.Title = "MVC Books Gallery";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    @foreach (var book in Model)
    {
        <div class="col-md-3">

            <h4>@Html.ActionLink(book.DisplayText, "Detail", new { id = book.Id} )</h4>
            
            <a href="@Url.Action("Detail", new {id = book.Id } )">
            <img src="/Images/@book.CoverImageFileName"
                 alt="@book.DisplayText"
                 class="img-responsive" />
            </a>

        </div>
    }
</div>

MVCMovieGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC Book Gallery</title>
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Book Gallery", "Index", "BookGallery", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Add menu items here -->
                </ul>
            </div>
        </div>
    </div>
    @if (ViewBag.ShowBackBar != null && ViewBag.ShowBackBar)
    {
        <div class="backbar">
            <div class="container">
                @Html.ActionLink("Return to List", "Index", null, new { @class = "btn btn-default" })
                @*<a class="btn btn-default" href="/">Return to List</a>*@
            </div>
        </div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MVC Book Gallery</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>